name: Ruby Linter

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install dependencies
        run: bundle install

      - name: Run linter
        run:  bash -c "bundle exec rake standard"